# Generated by Django 3.2.8 on 2022-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='photo',
            field=models.ImageField(upload_to='heroes/photo/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
